// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/drornir/cue-example-api/api

package api

#User: {
	ID:    string
	Name:  string
	Email: string
}

#UserPermissions: {
	UserID: string
	Permissions: [...#Permission] @go(,[]Permission)
}

#Permission: {
	Resources: #ResourcesSelector
	Allows: [...#ResourceAction] @go(,[]ResourceAction)
	Denies: [...#ResourceAction] @go(,[]ResourceAction)
}

#ResourcesSelector: string

#ResourceAction: string
